name: Deploy to EC2

on: 
    workflow_dispatch:

jobs:
  deploy:
    runs-on: self-hosted  # セルフホステッドランナーを使用
    steps:
    - name: Checkout code
      uses: actions/checkout@v2  # リポジトリをチェックアウト

    - name: Install unzip
      run: sudo apt-get update && sudo apt-get install -y unzip

    - name: Install AWS CLI
      run: |
        curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
        unzip -o awscliv2.zip
        sudo ./aws/install --update

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}  # 例: us-east-1

     # デプロイする
    - name: Execute deployment script on EC2
      run: |
        aws ssm send-command \
          --document-name "AWS-RunShellScript" \
          --document-version "1" \
          --targets "Key=instanceids,Values=${{ secrets.AWS_EC2_INSTANCE_ID }}'" \
          --parameters '{"commands":["cd /home/ec2-user && git pull && npm install && pm2 restart all"]}' \
          --timeout-seconds 600 \
          --max-concurrency "50" \
          --max-errors "0" \
          --region '${{ secrets.AWS_REGION }}' \
          --output text